/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as MetodologiaRouteImport } from './routes/metodologia'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as CalculadoraMorarSozinhoRouteImport } from './routes/calculadora-morar-sozinho'
import { Route as CalculadoraCustoPetRouteImport } from './routes/calculadora-custo-pet'
import { Route as CalculadoraCustoMudancaRouteImport } from './routes/calculadora-custo-mudanca'
import { Route as CalculadoraCustoCarroRouteImport } from './routes/calculadora-custo-carro'
import { Route as CalculadoraContaDeLuzRouteImport } from './routes/calculadora-conta-de-luz'
import { Route as CalculadoraAssinaturasRouteImport } from './routes/calculadora-assinaturas'
import { Route as IndexRouteImport } from './routes/index'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodologiaRoute = MetodologiaRouteImport.update({
  id: '/metodologia',
  path: '/metodologia',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadoraMorarSozinhoRoute = CalculadoraMorarSozinhoRouteImport.update({
  id: '/calculadora-morar-sozinho',
  path: '/calculadora-morar-sozinho',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadoraCustoPetRoute = CalculadoraCustoPetRouteImport.update({
  id: '/calculadora-custo-pet',
  path: '/calculadora-custo-pet',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadoraCustoMudancaRoute = CalculadoraCustoMudancaRouteImport.update({
  id: '/calculadora-custo-mudanca',
  path: '/calculadora-custo-mudanca',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadoraCustoCarroRoute = CalculadoraCustoCarroRouteImport.update({
  id: '/calculadora-custo-carro',
  path: '/calculadora-custo-carro',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadoraContaDeLuzRoute = CalculadoraContaDeLuzRouteImport.update({
  id: '/calculadora-conta-de-luz',
  path: '/calculadora-conta-de-luz',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadoraAssinaturasRoute = CalculadoraAssinaturasRouteImport.update({
  id: '/calculadora-assinaturas',
  path: '/calculadora-assinaturas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calculadora-assinaturas': typeof CalculadoraAssinaturasRoute
  '/calculadora-conta-de-luz': typeof CalculadoraContaDeLuzRoute
  '/calculadora-custo-carro': typeof CalculadoraCustoCarroRoute
  '/calculadora-custo-mudanca': typeof CalculadoraCustoMudancaRoute
  '/calculadora-custo-pet': typeof CalculadoraCustoPetRoute
  '/calculadora-morar-sozinho': typeof CalculadoraMorarSozinhoRoute
  '/contato': typeof ContatoRoute
  '/metodologia': typeof MetodologiaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calculadora-assinaturas': typeof CalculadoraAssinaturasRoute
  '/calculadora-conta-de-luz': typeof CalculadoraContaDeLuzRoute
  '/calculadora-custo-carro': typeof CalculadoraCustoCarroRoute
  '/calculadora-custo-mudanca': typeof CalculadoraCustoMudancaRoute
  '/calculadora-custo-pet': typeof CalculadoraCustoPetRoute
  '/calculadora-morar-sozinho': typeof CalculadoraMorarSozinhoRoute
  '/contato': typeof ContatoRoute
  '/metodologia': typeof MetodologiaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calculadora-assinaturas': typeof CalculadoraAssinaturasRoute
  '/calculadora-conta-de-luz': typeof CalculadoraContaDeLuzRoute
  '/calculadora-custo-carro': typeof CalculadoraCustoCarroRoute
  '/calculadora-custo-mudanca': typeof CalculadoraCustoMudancaRoute
  '/calculadora-custo-pet': typeof CalculadoraCustoPetRoute
  '/calculadora-morar-sozinho': typeof CalculadoraMorarSozinhoRoute
  '/contato': typeof ContatoRoute
  '/metodologia': typeof MetodologiaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calculadora-assinaturas'
    | '/calculadora-conta-de-luz'
    | '/calculadora-custo-carro'
    | '/calculadora-custo-mudanca'
    | '/calculadora-custo-pet'
    | '/calculadora-morar-sozinho'
    | '/contato'
    | '/metodologia'
    | '/privacidade'
    | '/sobre'
    | '/termos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calculadora-assinaturas'
    | '/calculadora-conta-de-luz'
    | '/calculadora-custo-carro'
    | '/calculadora-custo-mudanca'
    | '/calculadora-custo-pet'
    | '/calculadora-morar-sozinho'
    | '/contato'
    | '/metodologia'
    | '/privacidade'
    | '/sobre'
    | '/termos'
  id:
    | '__root__'
    | '/'
    | '/calculadora-assinaturas'
    | '/calculadora-conta-de-luz'
    | '/calculadora-custo-carro'
    | '/calculadora-custo-mudanca'
    | '/calculadora-custo-pet'
    | '/calculadora-morar-sozinho'
    | '/contato'
    | '/metodologia'
    | '/privacidade'
    | '/sobre'
    | '/termos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalculadoraAssinaturasRoute: typeof CalculadoraAssinaturasRoute
  CalculadoraContaDeLuzRoute: typeof CalculadoraContaDeLuzRoute
  CalculadoraCustoCarroRoute: typeof CalculadoraCustoCarroRoute
  CalculadoraCustoMudancaRoute: typeof CalculadoraCustoMudancaRoute
  CalculadoraCustoPetRoute: typeof CalculadoraCustoPetRoute
  CalculadoraMorarSozinhoRoute: typeof CalculadoraMorarSozinhoRoute
  ContatoRoute: typeof ContatoRoute
  MetodologiaRoute: typeof MetodologiaRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  SobreRoute: typeof SobreRoute
  TermosRoute: typeof TermosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metodologia': {
      id: '/metodologia'
      path: '/metodologia'
      fullPath: '/metodologia'
      preLoaderRoute: typeof MetodologiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadora-morar-sozinho': {
      id: '/calculadora-morar-sozinho'
      path: '/calculadora-morar-sozinho'
      fullPath: '/calculadora-morar-sozinho'
      preLoaderRoute: typeof CalculadoraMorarSozinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadora-custo-pet': {
      id: '/calculadora-custo-pet'
      path: '/calculadora-custo-pet'
      fullPath: '/calculadora-custo-pet'
      preLoaderRoute: typeof CalculadoraCustoPetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadora-custo-mudanca': {
      id: '/calculadora-custo-mudanca'
      path: '/calculadora-custo-mudanca'
      fullPath: '/calculadora-custo-mudanca'
      preLoaderRoute: typeof CalculadoraCustoMudancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadora-custo-carro': {
      id: '/calculadora-custo-carro'
      path: '/calculadora-custo-carro'
      fullPath: '/calculadora-custo-carro'
      preLoaderRoute: typeof CalculadoraCustoCarroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadora-conta-de-luz': {
      id: '/calculadora-conta-de-luz'
      path: '/calculadora-conta-de-luz'
      fullPath: '/calculadora-conta-de-luz'
      preLoaderRoute: typeof CalculadoraContaDeLuzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadora-assinaturas': {
      id: '/calculadora-assinaturas'
      path: '/calculadora-assinaturas'
      fullPath: '/calculadora-assinaturas'
      preLoaderRoute: typeof CalculadoraAssinaturasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalculadoraAssinaturasRoute: CalculadoraAssinaturasRoute,
  CalculadoraContaDeLuzRoute: CalculadoraContaDeLuzRoute,
  CalculadoraCustoCarroRoute: CalculadoraCustoCarroRoute,
  CalculadoraCustoMudancaRoute: CalculadoraCustoMudancaRoute,
  CalculadoraCustoPetRoute: CalculadoraCustoPetRoute,
  CalculadoraMorarSozinhoRoute: CalculadoraMorarSozinhoRoute,
  ContatoRoute: ContatoRoute,
  MetodologiaRoute: MetodologiaRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  SobreRoute: SobreRoute,
  TermosRoute: TermosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
